version: 0.2

env:
  variables:
    COSIGN_EXPERIMENTAL: "1"  # Enable keyless signing

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing cosign..."
      - curl -O -L "https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64"
      - sudo mv cosign-linux-amd64 /usr/local/bin/cosign
      - sudo chmod +x /usr/local/bin/cosign
      - cosign version

  pre_build:
    commands:
      - echo "Signing Service Started"
      - echo "Artifact to sign: $ARTIFACT_KEY"

  build:
    commands:
      - |
        # Download artifact from S3
        aws s3 cp s3://${BUCKET}/${ARTIFACT_KEY} ./${ARTIFACT_KEY}

        # Calculate SHA256 digest
        SHA256=$(sha256sum ${ARTIFACT_KEY} | awk '{print $1}')
        echo "Artifact SHA256: $SHA256"

        # Keyless signing using OIDC identity from CodeBuild
        cosign sign-blob \
          --bundle ${ARTIFACT_KEY}.bundle \
          --yes \
          ${ARTIFACT_KEY}

        # Extract Rekor log index from bundle
        REKOR_LOG_INDEX=$(cat ${ARTIFACT_KEY}.bundle | \
          jq -r '.verificationMaterial.tlogEntries[0].logIndex')

        echo "Rekor Log Index: $REKOR_LOG_INDEX"

        # Upload signature bundle to S3
        aws s3 cp ${ARTIFACT_KEY}.bundle s3://${BUCKET}/${ARTIFACT_KEY}.bundle

        # Record in DynamoDB trust ledger
        aws dynamodb put-item \
          --table-name ${LEDGER_TABLE:-trust-ledger} \
          --item "{
            \"object_key\": {\"S\": \"s3://${BUCKET}/${ARTIFACT_KEY}\"},
            \"digest\": {\"S\": \"sha256:${SHA256}\"},
            \"rekor_entry_id\": {\"S\": \"${REKOR_LOG_INDEX}\"},
            \"status\": {\"S\": \"verified\"},
            \"timestamp\": {\"S\": \"$(date -u +%Y-%m-%dT%H:%M:%S)\"},
            \"signing_method\": {\"S\": \"cosign-keyless\"},
            \"rekor_verified\": {\"BOOL\": true},
            \"details\": {\"S\": \"Signed with Sigstore keyless (OIDC)\"}
          }"

        echo "Signing complete - artifact recorded in trust ledger"
