#!/bin/bash
# SalsaGate Installation Script
# Usage: ./install.sh --staging-bucket BUCKET --website-bucket BUCKET --ledger-table TABLE --signer-project PROJECT --region REGION
# Or: ./install.sh --interactive

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
REGION="us-east-1"
LEDGER_TABLE="trust-ledger"
SIGNER_PROJECT="salsag-artifact-signer"

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATES_DIR="${SCRIPT_DIR}/templates"

print_banner() {
    echo -e "${BLUE}"
    echo "╔═══════════════════════════════════════════╗"
    echo "║         SalsaGate Installation            ║"
    echo "║   Supply Chain Security for CI/CD         ║"
    echo "╚═══════════════════════════════════════════╝"
    echo -e "${NC}"
}

print_step() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --staging-bucket    S3 bucket for staging artifacts (required)"
    echo "  --website-bucket    S3 bucket for production website (required)"
    echo "  --ledger-table      DynamoDB table name (default: trust-ledger)"
    echo "  --signer-project    CodeBuild signer project name (default: salsag-artifact-signer)"
    echo "  --region            AWS region (default: us-east-1)"
    echo "  --interactive       Interactive mode - prompts for values"
    echo "  --help              Show this help message"
    echo ""
    echo "Example:"
    echo "  $0 --staging-bucket my-staging --website-bucket my-website --region us-east-1"
    exit 1
}

interactive_mode() {
    print_banner
    echo "Running in interactive mode..."
    echo ""

    read -p "S3 Staging Bucket name: " STAGING_BUCKET
    read -p "S3 Website Bucket name: " WEBSITE_BUCKET
    read -p "DynamoDB Ledger Table [trust-ledger]: " input
    LEDGER_TABLE="${input:-trust-ledger}"
    read -p "CodeBuild Signer Project [salsag-artifact-signer]: " input
    SIGNER_PROJECT="${input:-salsag-artifact-signer}"
    read -p "AWS Region [us-east-1]: " input
    REGION="${input:-us-east-1}"
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --staging-bucket)
                STAGING_BUCKET="$2"
                shift 2
                ;;
            --website-bucket)
                WEBSITE_BUCKET="$2"
                shift 2
                ;;
            --ledger-table)
                LEDGER_TABLE="$2"
                shift 2
                ;;
            --signer-project)
                SIGNER_PROJECT="$2"
                shift 2
                ;;
            --region)
                REGION="$2"
                shift 2
                ;;
            --interactive)
                interactive_mode
                return
                ;;
            --help)
                usage
                ;;
            *)
                print_error "Unknown option: $1"
                usage
                ;;
        esac
    done
}

validate_inputs() {
    if [[ -z "$STAGING_BUCKET" ]]; then
        print_error "Staging bucket is required"
        usage
    fi
    if [[ -z "$WEBSITE_BUCKET" ]]; then
        print_error "Website bucket is required"
        usage
    fi
}

install_files() {
    print_banner
    echo "Installing SalsaGate with the following configuration:"
    echo "  Staging Bucket:  $STAGING_BUCKET"
    echo "  Website Bucket:  $WEBSITE_BUCKET"
    echo "  Ledger Table:    $LEDGER_TABLE"
    echo "  Signer Project:  $SIGNER_PROJECT"
    echo "  Region:          $REGION"
    echo ""

    # Create directories
    mkdir -p .github/workflows

    # Create salsag.yml
    print_step "Creating salsag.yml..."
    cat > salsag.yml << EOF
# SalsaGate Configuration
# Generated by install.sh

aws:
  region: ${REGION}
  staging_bucket: ${STAGING_BUCKET}
  ledger_table: ${LEDGER_TABLE}

logging:
  cloudwatch:
    level: "INFO"
    log_group: "/salsagate/deploy"
    stream_name: "verification-metrics"
    region: ${REGION}
EOF

    # Create buildspec.yml
    print_step "Creating buildspec.yml..."
    cat > buildspec.yml << 'BUILDSPEC'
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing SalsaG CLI..."
      - python3 -m pip install --upgrade pip
      - pip install git+https://github.com/tanishk97/salsaG-installation.git#subdirectory=salsag-cli
      - echo "Installing cosign..."
      - curl -O -L "https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64"
      - sudo mv cosign-linux-amd64 /usr/local/bin/cosign
      - sudo chmod +x /usr/local/bin/cosign

  pre_build:
    commands:
      - echo "Verifying artifact..."
      - |
        if salsaG verify --artifact index.tgz --config salsag.yml; then
          echo "Verification PASSED"
        else
          echo "Verification FAILED - blocking deployment"
          exit 1
        fi

  build:
    commands:
      - echo "Deploying verified artifact..."
BUILDSPEC

    # Append deployment command with actual bucket
    cat >> buildspec.yml << EOF
      - aws s3 cp s3://${STAGING_BUCKET}/index.tgz ./verified-index.tgz
      - tar -xzf verified-index.tgz
      - aws s3 sync . s3://${WEBSITE_BUCKET}/ --exclude "*.tgz" --exclude "*.yml" --exclude ".git/*"

  post_build:
    commands:
      - echo "Deployment complete"
EOF

    # Create GitHub workflow
    print_step "Creating .github/workflows/salsagate-pipeline.yml..."
    cat > .github/workflows/salsagate-pipeline.yml << EOF
name: SalsaGate Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '**.html'
      - '**.css'
      - '**.js'

env:
  AWS_REGION: ${REGION}
  STAGING_BUCKET: ${STAGING_BUCKET}
  WEBSITE_BUCKET: ${WEBSITE_BUCKET}

jobs:
  build-sign-deploy:
    runs-on: ubuntu-latest
    # For CodeBuild runner, use: runs-on: codebuild-YourProject-\${{ github.run_id }}-\${{ github.run_attempt }}

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install SalsaG CLI
        run: |
          pip install git+https://github.com/tanishk97/salsaG-installation.git#subdirectory=salsag-cli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${REGION}

      - name: Build Application
        run: |
          mkdir -p dist
          cp -r *.html dist/ 2>/dev/null || true
          cp -r *.css dist/ 2>/dev/null || true
          cp -r *.js dist/ 2>/dev/null || true
          cp -r assets dist/ 2>/dev/null || true

      - name: Package Artifact
        run: |
          cd dist && tar -czf ../index.tgz . && cd ..

      - name: Upload to Staging
        run: |
          aws s3 cp index.tgz s3://${STAGING_BUCKET}/index.tgz

      - name: Invoke Signing Service
        run: |
          BUILD_ID=\$(aws codebuild start-build \\
            --project-name ${SIGNER_PROJECT} \\
            --environment-variables-override name=ARTIFACT_KEY,value=index.tgz \\
            --query 'build.id' --output text)

          echo "Waiting for signing..."
          for i in {1..30}; do
            STATUS=\$(aws codebuild batch-get-builds --ids \$BUILD_ID --query 'builds[0].buildStatus' --output text)
            if [ "\$STATUS" = "SUCCEEDED" ]; then
              echo "Signing complete"
              break
            elif [ "\$STATUS" = "FAILED" ]; then
              echo "Signing failed"
              exit 1
            fi
            sleep 5
          done

      - name: Trigger Deployment Pipeline
        run: |
          aws codepipeline start-pipeline-execution --name your-pipeline-name || true
          echo "Deployment triggered"
EOF

    print_step "Installation complete!"
    echo ""
    echo -e "${GREEN}Next steps:${NC}"
    echo "1. Review and customize the generated files"
    echo "2. Set up AWS_ROLE_ARN secret in GitHub repository settings"
    echo "3. Push changes to trigger the pipeline"
    echo ""
    echo "Files created:"
    echo "  - salsag.yml"
    echo "  - buildspec.yml"
    echo "  - .github/workflows/salsagate-pipeline.yml"
}

# Main
if [[ $# -eq 0 ]]; then
    usage
fi

parse_args "$@"
validate_inputs
install_files
